// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkQxUzd9oKhOPmPuAOcdZdoEe4pGSzvFs',
    appId: '1:98214571932:web:39d712b5844a8c2ab6e259',
    messagingSenderId: '98214571932',
    projectId: 'my-healthy-b4fbc',
    authDomain: 'my-healthy-b4fbc.firebaseapp.com',
    storageBucket: 'my-healthy-b4fbc.appspot.com',
    measurementId: 'G-EQQRYXEPY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByaP0Ke68a69lhHYO6gyAE-08-tyHIuMw',
    appId: '1:98214571932:android:f5331f7575aa6c9fb6e259',
    messagingSenderId: '98214571932',
    projectId: 'my-healthy-b4fbc',
    storageBucket: 'my-healthy-b4fbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0AgQBvZS1HVKP7IpQ8EvmsvS4QQoyu6E',
    appId: '1:98214571932:ios:d65e0b21782058cdb6e259',
    messagingSenderId: '98214571932',
    projectId: 'my-healthy-b4fbc',
    storageBucket: 'my-healthy-b4fbc.appspot.com',
    iosBundleId: 'com.example.myhealthyfoodAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0AgQBvZS1HVKP7IpQ8EvmsvS4QQoyu6E',
    appId: '1:98214571932:ios:d65e0b21782058cdb6e259',
    messagingSenderId: '98214571932',
    projectId: 'my-healthy-b4fbc',
    storageBucket: 'my-healthy-b4fbc.appspot.com',
    iosBundleId: 'com.example.myhealthyfoodAdmin',
  );
}
